EXTRA_CFLAGS += -Iarch/arm/mach-msm

#obj-$(CONFIG_MACH_HTC) += devices.o
obj-$(CONFIG_MACH_HTC_MSM7X27) += devices_htc.o msm_vibrator.o htc_wifi_nvs.o htc_awb_cal.o
obj-$(CONFIG_MACH_MSM7X27_LIBERTY) += board-liberty-rfkill.o htc_bluetooth.o
obj-$(CONFIG_MACH_MSM7X27_LIBERTY) += board-liberty.o board-liberty-keypad.o board-liberty-panel.o
obj-$(CONFIG_MACH_MSM7X27_LIBERTY) += board-liberty-mmc.o board-liberty-wifi.o board-liberty-microp.o htc_tp_cal.o
